version: '3'
services:
  receipt-processor:
    container_name: receipt-processor
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    image: receipt-processor:latest
    ports:
      - "8080:8080"
    environment:
      - "GIN_MODE=release"
      - "BIND_ADDRESS=0.0.0.0"
